# Fine-tuning RadBert #
Full parameter fine tuning of RadBERT model (RadBERT-RoBERTa-4m model from the RadBERT paper). Fine tuning carried out on the multi-label muti-class classification of reports, where each report can have multiple labels (For ex, a report can havel label consolidation-right and consolidation-2)

In [1]:
import os
import datetime
import codecs
from itertools import product

import numpy as np
import pandas as pd

import torch
from torch import nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from torch.utils.tensorboard import SummaryWriter

import transformers
from transformers import AutoTokenizer, AutoModel
from transformers import pipeline

/home/users/pranav.rao/miniconda3/envs/TutorialCuda/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
pd.set_option('display.max_rows', 50)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

torch.set_printoptions(linewidth=200)

In [3]:
# Get cpu, gpu or mps device for training.
device = (
    "cuda"
    if torch.cuda.is_available()
    else "mps"
    if torch.backends.mps.is_available()
    else "cpu"
)
print(f"Using {device} device")

Using cuda device


## Forward pass ##
Implementing RadBERTMultiClassMulti Label PyTorch Model

In [4]:
class RadBERTMultiClassMultiLabel(nn.Module):
    """
    RadBERTMultiClassMultiLabel: Model expects batches of natural language sentences, will
    classify reports with multiple label
    """
    def __init__(self, num_classes, checkpoint):
        super().__init__()
        self.num_classes = num_classes
        self.checkpoint = checkpoint
        self.tokenizer = AutoTokenizer.from_pretrained(self.checkpoint)
        self.transformer_encoder = AutoModel.from_pretrained(self.checkpoint)
        self.transformer_encoder_hidden_size = self.transformer_encoder.config.hidden_size
        self.linear_classifier = nn.Linear(self.transformer_encoder_hidden_size, self.num_classes)
    
    def forward(self, x):
        tokenized_inp = self.tokenizer(x, padding=True, truncation=True, return_tensors='pt')
        encoder_out = self.transformer_encoder(**tokenized_inp)
        logits = self.linear_classifier(encoder_out.last_hidden_state[:, 0, :])
        return logits


In [5]:
checkpoint = 'UCSD-VA-health/RadBERT-RoBERTa-4m'
#radbert_multi_model = RadBERTMultiClassMultiLabel(321, checkpoint).to(device)
radbert_multi_model = RadBERTMultiClassMultiLabel(322, checkpoint)

Some weights of RobertaModel were not initialized from the model checkpoint at UCSD-VA-health/RadBERT-RoBERTa-4m and are newly initialized: ['roberta.pooler.dense.weight', 'roberta.pooler.dense.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [6]:
print(radbert_multi_model)
print(list(map(lambda x : x.shape, radbert_multi_model.parameters())))

RadBERTMultiClassMultiLabel(
  (transformer_encoder): RobertaModel(
    (embeddings): RobertaEmbeddings(
      (word_embeddings): Embedding(50265, 768, padding_idx=1)
      (position_embeddings): Embedding(514, 768, padding_idx=1)
      (token_type_embeddings): Embedding(1, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): RobertaEncoder(
      (layer): ModuleList(
        (0-11): 12 x RobertaLayer(
          (attention): RobertaAttention(
            (self): RobertaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): RobertaSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
      

## Custom Loss function ##
Custom loss function for multi class multi label classification to handle uncertain tags (tags have value 0 -> absent, 1 -> present, -100 -> uncertain)

In [7]:
class MultiClassMultiLabel(nn.Module):
    def __init__(self, uncertain_label):
        super(MultiClassMultiLabel, self).__init__()
        self.uncertain_label = uncertain_label
    
    def forward(self, output, target):
        certain_mask = (target != self.uncertain_label)
        loss_func = nn.MultiLabelSoftMarginLoss(weight=certain_mask.type(torch.float))
        return loss_func(output, target)

In [8]:
multiclass_multilabel_loss = MultiClassMultiLabel(-100)

### Testing MultiClassMultiLabel loss function ###

In [9]:
logit_tensor = torch.Tensor([[-1.0, 2.0, 1.0, 5.0, -3.0], [4.0, -2.0, 1.0, -1.0, 2.5]])
target_tensor_act = torch.Tensor([[0, 1, -100, 0, 0], [1, -100, 0, 0, 1]])

In [10]:
#certain_mask = (target_tensor_act != -100)
#print(certain_mask.type(torch.float))
#loss_func = nn.MultiLabelSoftMarginLoss(weight=(certain_mask).type(torch.float))
#print(loss_func(logit_tensor, target_tensor_act))
print(multiclass_multilabel_loss(logit_tensor, target_tensor_act))

tensor(0.7219)


In [11]:
import math
from math import log, exp

def log_sigmoid(x):
    return log(1/(1+exp(-1*x)))

In [12]:
loss1 = -1 * (1.0 * log_sigmoid(1.0) + 1.0 * log_sigmoid(2.0) + 0.0 * log_sigmoid(-1.0) + 1.0 * log_sigmoid(-5.0) + 1.0 * log_sigmoid(3.0)) / 5.0
loss2 = -1 * (1.0 * log_sigmoid(4.0) + 0.0 * log_sigmoid(2.0) + 1.0 * log_sigmoid(-1.0) + 1.0 * log_sigmoid(1.0) + 1.0 * log_sigmoid(2.5)) / 5.0

print(loss1)
print(loss2)
print((loss1 + loss2)/2.0)

1.0990984797248111
0.34471260744936094
0.721905543587086


## Custom DataLoader and Dataset ##
Read csv file, get the report from path and prepare the data

In [13]:
class ReportTagsDataset(Dataset):
    def __init__(self, tags_csv_file, report_base_path, text_transform=None, target_transform=None):
        self.report_base_path = report_base_path
        self.tags_csv_file = tags_csv_file

        self.tags_df = pd.read_csv(self.tags_csv_file)
        self.column_names = list(self.tags_df.columns.values)
        self.column_names[0] = 'filename'
        self.tags_df.columns = self.column_names

        self.text_transform = text_transform
        self.target_transform = target_transform
    
    def __len__(self):
        return self.tags_df.shape[0]
    
    def __getitem__(self, index):
        report_path = os.path.join(self.report_base_path, self.tags_df.iloc[index, 0].split('/')[-1] + '.txt')
        #report_text = open(report_path).read()
        report_text = codecs.open(report_path, 'r', encoding='utf-8', errors='ignore').read()
        target_list = torch.Tensor(list(self.tags_df.iloc[index][1:]))
        return report_text, target_list

In [14]:
#report_base_path = "/models_common_e2e/cxr_data/reports/training"
train_reports_base_path = '/home/users/pranav.rao/MiniTasks/Radbert/data/train'
test_reports_base_path = '/home/users/pranav.rao/MiniTasks/Radbert/data/test'
train_tags_file = '/home/users/pranav.rao/Downloads/report_tags_25k_train.csv'
test_tags_file = '/home/users/pranav.rao/Downloads/report_tags_25k_train.csv'

In [15]:
train_data = ReportTagsDataset(train_tags_file, train_reports_base_path)
test_data = ReportTagsDataset(test_tags_file, test_reports_base_path)

In [16]:
train_dataloader = DataLoader(train_data, batch_size=32, shuffle=True)
test_dataloader = DataLoader(test_data, batch_size=32, shuffle=True)

### Testing Dataset and DataLoader ###

In [17]:
# Display image and label.
train_features, train_labels = next(iter(train_dataloader))

FileNotFoundError: [Errno 2] No such file or directory: '/models_common_e2e/cxr_data/reports/training/ca.phaseii.unit2.1937e108a204179f11fd8e8bf31dd7ec60ced1ea73b3b588270f2573.txt'

In [34]:
print(train_features)
print(train_labels)
print(f"Feature batch shape: {len(train_features)}")
print(f"Labels batch shape: {len(train_labels)}")
report_text = train_features[0]
print(report_text)
label = train_labels[0]
print(f"Label: {label}")

('6434328|5725519|X-Ray Chest PA/AP View of 06-MAY-2018:\nResults:\nNo focal lesion seen in the lung parenchyma. \nCP angles and domes of the diaphragm are normal.\nBoth hila are normal. Pulmonary vasculature is normal.\nCardiac size and configuration is normal.\nTrachea is central; no mediastinal shift is seen.\nBony thorax and soft tissues of the chest wall are normal.\nIMPRESSION: No abnormality detected in the view obtained.\n6434328|5725519|X-Ray Chest PA/AP View of 06-MAY-2018:\nResults:\nNo focal lesion seen in the lung parenchyma. \nCP angles and domes of the diaphragm are normal.\nBoth hila are normal. Pulmonary vasculature is normal.\nCardiac size and configuration is normal.\nTrachea is central; no mediastinal shift is seen.\nBony thorax and soft tissues of the chest wall are normal.\nIMPRESSION: No abnormality detected in the view obtained.', '6915839|6146524|X-Ray Chest PA/AP View of 27-OCT-2018:\nBoth lung fields are clear except small nodular opacity in left parahilar re

In [45]:
logit_tensor = radbert_multi_model(train_features)

In [47]:
print(logit_tensor)
print(logit_tensor.shape)

tensor([[-0.1485, -0.3681,  0.0774,  ..., -0.2707, -0.0061, -0.1722],
        [-0.1415, -0.3708,  0.1239,  ..., -0.2729, -0.0105, -0.1739],
        [-0.1658, -0.3611,  0.0246,  ..., -0.2912,  0.0304, -0.1404],
        ...,
        [-0.1485, -0.3477,  0.0417,  ..., -0.2952,  0.0045, -0.1395],
        [-0.1423, -0.3476,  0.0403,  ..., -0.3019, -0.0042, -0.1491],
        [-0.1514, -0.3525,  0.0412,  ..., -0.3050,  0.0014, -0.1509]], grad_fn=<AddmmBackward0>)
torch.Size([32, 322])


## Fine Tuning ##
Fine tuning the RadBERT model for tags prediction task

### Adam Optimizer ###
Using Adam optimizer with learning rate 3e-5, beta1 = 0.9, beta2 = 0.99, l2 weight decay of 0.01

In [19]:
lr = 3e-5
beta1 = 0.9
beta2 = 0.99
l2_weight_decay = 0.01

In [20]:
optimizer = torch.optim.Adam(radbert_multi_model.parameters(), lr=lr, betas=(beta1, beta2), weight_decay=l2_weight_decay)

In [21]:
def train_one_epoch(epoch_index, tb_writer):
    running_loss = 0.
    last_loss = 0.

    for i, data in enumerate(train_dataloader):
        inputs, labels = data
        optimizer.zero_grad()
        outputs = radbert_multi_model(inputs)

        # Compute the loss and its gradients
        loss = multiclass_multilabel_loss(outputs, labels)
        loss.backward()
        optimizer.step()

        # Gather data and report
        running_loss += loss.item()
        if i % 100 == 999:
            last_loss = running_loss / 100 # loss per batch
            print('  batch {} loss: {}'.format(i + 1, last_loss))
            tb_x = epoch_index * len(train_dataloader) + i + 1
            tb_writer.add_scalar('Loss/train', last_loss, tb_x)
            running_loss = 0.

    return last_loss

### The full fine-tuning loog ###

In [22]:
total_epochs = 5

In [24]:
# Initializing in a separate cell so we can easily add more epochs to the same run
timestamp = datetime.datetime.now().strftime('%Y%m%d_%H%M%S')
writer = SummaryWriter('runs/fashion_trainer_{}'.format(timestamp))
epoch_number = 0

for epoch in range(total_epochs):
    # Make sure gradient tracking is on, and do a pass over the data
    print('EPOCH {}:'.format(epoch_number + 1))
    radbert_multi_model.train(True)
    avg_loss = train_one_epoch(epoch_number, writer)

    # Set the model to evaluation mode, disabling dropout and using population, statistics for batch normalization
    running_vloss = 0.0
    radbert_multi_model.eval()

    # Disable gradient computation and reduce memory consumption.
    with torch.no_grad():
        for i, vdata in enumerate(train_dataloader):
            vinputs, vlabels = vdata
            voutputs = radbert_multi_model(vinputs)
            vloss = multiclass_multilabel_loss(voutputs, vlabels)
            running_vloss += vloss

    avg_vloss = running_vloss / (i + 1)
    print('LOSS train {} valid {}'.format(avg_loss, avg_vloss))

    # Log the running loss averaged per batch for both training and validation
    writer.add_scalars('Training vs. Validation Loss',
                    { 'Training' : avg_loss, 'Validation' : avg_vloss },
                    epoch_number + 1)
    writer.flush()
    model_path = '/home/users/pranav.rao/MiniTasks/Radbert/model_{}_{}'.format(timestamp, epoch_number)
    torch.save(radbert_multi_model.state_dict(), model_path)
    epoch_number += 1

EPOCH 1:


## Analyzing fine-tuned models ##

In [5]:
sentence_list = ["The report shows small right-sided pleural effusion", "The report shows small left-sided pleural effusion",\
    "The report shows large right-sided pleural effusion", "The report shows large left-sided pleural effusion",\
    "There are no abnormalities in the report",\
    "There is severe consolidation in the left side","There is severe consolidation in the right side",\
    "There is mild consolidation in the right side", "There is mild consolidation in the left side"
]

sentence1_base = "A <SizeModifier> <AbnormalReport> can be seen in the report in the <LocationModifier> part"
sentence2_base = "The report shows a <SizeModifier> <LocationModifier> <AbnormalReport>"
size_modifiers = ['small', 'large']
loc_modifiers = ['upper-left', 'lower-left', 'right-sided', 'left-sided']
abnormal_report = ['pleural effusion']

l1 = [sentence1_base.replace('<SizeModifier>', size_mod).replace('<LocationModifier>', loc_mod).replace('<AbnormalReport>', ab_rep) for size_mod, loc_mod, ab_rep in product(size_modifiers, loc_modifiers, abnormal_report)]
l2 = [sentence2_base.replace('<SizeModifier>', size_mod).replace('<LocationModifier>', loc_mod).replace('<AbnormalReport>', ab_rep) for size_mod, loc_mod, ab_rep in product(size_modifiers, loc_modifiers, abnormal_report)]

negative_sentences = ['The report shows no pleural effusion', 'The report shows no consolidation on any side']
all_sentence_list = l1 + l2 + negative_sentences + sentence_list[4:]

In [6]:
print('\n'.join(all_sentence_list))

A small pleural effusion can be seen in the report in the upper-left part
A small pleural effusion can be seen in the report in the lower-left part
A small pleural effusion can be seen in the report in the right-sided part
A small pleural effusion can be seen in the report in the left-sided part
A large pleural effusion can be seen in the report in the upper-left part
A large pleural effusion can be seen in the report in the lower-left part
A large pleural effusion can be seen in the report in the right-sided part
A large pleural effusion can be seen in the report in the left-sided part
The report shows a small upper-left pleural effusion
The report shows a small lower-left pleural effusion
The report shows a small right-sided pleural effusion
The report shows a small left-sided pleural effusion
The report shows a large upper-left pleural effusion
The report shows a large lower-left pleural effusion
The report shows a large right-sided pleural effusion
The report shows a large left-sid

In [7]:
def calc_cosine_sim_matrix(sentence_embeddings):
    #stacked_sentence_embeddings = torch.stack(sentence_embeddings)
    stacked_sentence_embeddings = sentence_embeddings
    # Calculate the cosine similarity matrix
    cosine_sim_matrix = F.cosine_similarity(stacked_sentence_embeddings.unsqueeze(1), stacked_sentence_embeddings.unsqueeze(0), dim=2)
    return stacked_sentence_embeddings, cosine_sim_matrix

In [38]:
def get_sentence_embeddings(model, input):
    with torch.no_grad():
        tokenized_inp = model.tokenizer(input, padding=True, truncation=True, return_tensors='pt')
        encoder_out = model.transformer_encoder(**tokenized_inp)
    return encoder_out.last_hidden_state[:, 0, :]

In [57]:
model_path = '/home/users/pranav.rao/MiniTasks/Radbert/ModelPool/model_20230912_143355_1'
checkpoint = 'UCSD-VA-health/RadBERT-RoBERTa-4m'
radbert_multi_model = RadBERTMultiClassMultiLabel(322, checkpoint)
radbert_multi_model.load_state_dict(torch.load(model_path))

Some weights of RobertaModel were not initialized from the model checkpoint at UCSD-VA-health/RadBERT-RoBERTa-4m and are newly initialized: ['roberta.pooler.dense.weight', 'roberta.pooler.dense.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


<All keys matched successfully>

In [58]:
all_embeddings = get_sentence_embeddings(radbert_multi_model, all_sentence_list)

In [59]:
print(all_embeddings)
print(all_embeddings.shape)

tensor([[-0.0171,  0.2717, -0.0811,  ..., -2.2577,  0.0076,  0.4063],
        [-0.0182,  0.2700, -0.0807,  ..., -2.2609,  0.0092,  0.4046],
        [-0.0166,  0.2668, -0.0799,  ..., -2.2567,  0.0055,  0.4036],
        ...,
        [-0.0158,  0.2848, -0.1071,  ..., -2.2348,  0.0132,  0.3916],
        [-0.0152,  0.2882, -0.1051,  ..., -2.2295,  0.0123,  0.3890],
        [-0.0145,  0.2867, -0.1065,  ..., -2.2222,  0.0187,  0.3879]])
torch.Size([23, 768])


In [60]:
_, cosine_sim = calc_cosine_sim_matrix(all_embeddings)

In [61]:
print(cosine_sim)

tensor([[1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 0.9999, 0.9999, 0.9998, 0.9999, 0.9999, 0.9999, 0.9998, 0.9998, 0.9995, 0.9994, 0.9994, 0.9995, 0.9995, 0.9995, 0.9995],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 0.9999, 0.9999, 0.9998, 0.9999, 0.9998, 0.9999, 0.9998, 0.9998, 0.9995, 0.9994, 0.9994, 0.9995, 0.9995, 0.9995, 0.9995],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 0.9999, 0.9999, 0.9999, 0.9999, 0.9998, 0.9999, 0.9999, 0.9999, 0.9995, 0.9995, 0.9994, 0.9995, 0.9995, 0.9995, 0.9995],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 0.9999, 0.9999, 0.9999, 0.9999, 0.9998, 0.9999, 0.9998, 0.9999, 0.9995, 0.9995, 0.9994, 0.9995, 0.9995, 0.9995, 0.9995],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 0.9999, 0.9999, 0.9998, 0.9998, 0.9999, 0.9999, 0.9998, 0.9999, 0.9995, 0.9995, 0.9994, 0.9995, 0.9995, 0.9995, 0.9995],
        [1.0000, 1.0000, 1.000

## Analysing the predictions ##

In [62]:
def get_predictions(model, input):
    with torch.no_grad():
        tokenized_inp = model.tokenizer(input, padding=True, truncation=True, return_tensors='pt')
        encoder_out = model.transformer_encoder(**tokenized_inp)
        logits = model.linear_classifier(encoder_out.last_hidden_state[:, 0, :])
        return logits

In [63]:
predictions = get_predictions(radbert_multi_model, all_sentence_list)

In [64]:
print(predictions)
print(predictions.shape)
print(predictions.argmax(dim=-1))

tensor([[-3.8206, -3.8873, -3.7434,  ..., -3.7868, -3.0926, -3.8059],
        [-3.8201, -3.8872, -3.7439,  ..., -3.7871, -3.0925, -3.8057],
        [-3.8199, -3.8880, -3.7429,  ..., -3.7862, -3.0920, -3.8055],
        ...,
        [-3.8062, -3.8835, -3.7301,  ..., -3.7826, -3.0944, -3.8023],
        [-3.8066, -3.8833, -3.7303,  ..., -3.7822, -3.0946, -3.8019],
        [-3.8068, -3.8829, -3.7300,  ..., -3.7826, -3.0946, -3.8022]])
torch.Size([23, 322])
tensor([224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224])


In [65]:
df_tags = pd.read_csv('/home/users/pranav.rao/MiniTasks/Radbert/report_tags_25k_train.csv')

In [67]:
print(df_tags.head())
print(df_tags.describe())

                                          Unnamed: 0  airspacedisease  perihilarairspacedisease  bronchiolitis  vascularprominence  vascularcongestion  perihilarcoarsening  hilarprominence  steeplesign  peribronchialthickening  interstitialthickening  interlobularseptalthickening  tortuousaorta  hyperinflation  emphysema  copd  bronchitis  markings  pneumonia  unfoldedaorta  chroniclungdisease  abscess  airbronchogram  aircrescent  airtrapping  apicalcap  aorticcalcification  atelectasis  azygosfissure  bluntedcp  border  bronchiectasis  bronchocele  bulla  bullousemphysema  calcification  carcinoma  cardiomegaly  cavity  consolidation  cyst  degenspine  diaphragmborder  edema  effusion  fibrosis  justfibrosis  fissuralshift  fissuralthickening  fracture  oldfracture  ribfracture  ribfractureall  claviclefracture  femurfracture  granuloma  groundglass  haziness  heartborder  hydropneumothorax  juxtaphrenicpeak  kerley  lesion  bullouslesion  lymphadenopathy  mass  bonemetastasis  \
0  

In [68]:
columns = list(df_tags.columns.values)
print(columns[224])

other
